// Flutter's core Material widget library (AlertDialog, TextField, buttons…).
import 'package:flutter/material.dart';
// Gives access to Clipboard (used for copy/paste of DSL and SVG text).
import 'package:flutter/services.dart';
// Custom monospace font (Courier Prime) used throughout the app's UI.
import 'package:google_fonts/google_fonts.dart';

// App-wide theme (colors, surfaces) read via AppThemeNotifier.read(context).
import '../widgets/app_theme.dart';
// Core data models: NodeData, LineData, StartArrowData, GraphState, etc.
import '../models.dart';
// DSL <-> GraphState conversion (DslCodec) and SVG export (SvgExporter).
import '../import_export.dart';
// SavedExport model — a persisted (name, dsl) pair shown in export history.
import '../persistence.dart';
// Simulators for the three automata families: NFA/DFA, PDA, and TM,
// plus their result enums (SimResult, PdaSimResult, TmResult) and the
// blank-tape constant (kBlank) used when rendering TM tapes.
import '../simulator.dart';
// Only need the AutomataMode enum from the drawer file (ndfa/regex/pda/tm),
// used to decide which simulator to run inside the black-box runner.
import '../widgets/automata_drawer.dart' show AutomataMode;

// ─────────────────────────────────────────────────────────────────────────────
//  showExportDialog
//
//  Displays the "Export" dialog: shows the current graph's DSL text (already
//  copied to the clipboard by the caller before this dialog opens), and lets
//  the user export as SVG, export as LaTeX, save the export for later reuse,
//  copy the DSL again, or just close the dialog.
// ─────────────────────────────────────────────────────────────────────────────
void showExportDialog(
  BuildContext context, {
  // The DSL text representing the current graph, already generated by caller.
  required String dsl,
  // How many exports have been saved so far — used to seed a default name
  // like "Export 4" in the text field.
  required int savedExportCount,
  // Current graph data, needed for SVG export (SvgExporter needs raw shapes).
  required Map<String, NodeData> nodes,
  required Map<String, LineData> lines,
  required StartArrowData? startArrow,
  // Full graph state, needed for the LaTeX export sub-dialog.
  required GraphState graphState,
  // Callback invoked when the user taps "Save" — persists (name, dsl) as a
  // SavedExport somewhere the caller manages (e.g. a list in local storage).
  required void Function(String name, String dsl) onSave,
}) {
  // Grab the current theme once; `read` (not `watch`) because this dialog's
  // colors don't need to react to theme changes while it's open.
  final theme = AppThemeNotifier.read(context);
  // Text field controller pre-filled with a default "Export N" name, where
  // N is one more than however many exports already exist.
  final nameController = TextEditingController(text: 'Export ${savedExportCount + 1}');

  showDialog(
    context: context,
    // `ctx` is the dialog's own BuildContext, distinct from the outer
    // `context` captured above — used for Navigator.pop calls below so we
    // pop precisely this dialog even if others are stacked on top later.
    builder: (ctx) => AlertDialog(
      // Match the dialog's surface color to the app theme's card/surface color.
      backgroundColor: theme.surface,
      shape: RoundedRectangleBorder(
        // Rounded corners consistent with the rest of the app's dialogs.
        borderRadius: BorderRadius.circular(12),
        // Subtle border so the dialog reads clearly against the backdrop.
        side: BorderSide(color: theme.borderMid),
      ),
      title: Text(
        'Export',
        style: GoogleFonts.courierPrime(
          fontWeight: FontWeight.bold,
          color: theme.textLight,
        ),
      ),
      content: SizedBox(
        // Let the dialog stretch to its maximum allowed width rather than
        // shrink-wrapping the content, so the DSL preview box has room.
        width: double.maxFinite,
        child: Column(
          // Column only takes as much vertical space as its children need.
          mainAxisSize: MainAxisSize.min,
          // Left-align all children instead of centering them.
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Editable name field — the value the user gives this export
            // when they hit Save.
            TextField(
              controller: nameController,
              style: GoogleFonts.courierPrime(color: theme.textLight, fontSize: 13),
              decoration: InputDecoration(
                labelText: 'Save Name',
                border: const OutlineInputBorder(),
              ),
            ),
            // Fixed vertical gap between the name field and the note below.
            const SizedBox(height: 12),
            // Informational note: the DSL was already placed on the
            // clipboard by the caller before this dialog was shown.
            Text(
              'Copied to clipboard.',
              style: GoogleFonts.courierPrime(fontSize: 13, color: theme.textMid),
            ),
            const SizedBox(height: 10),
            // Scrollable, height-capped box that previews the DSL text so
            // the user can review (and select/copy) it without the dialog
            // growing unbounded for large graphs.
            ConstrainedBox(
              constraints: const BoxConstraints(maxHeight: 320),
              child: Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  // Slightly different background than the dialog surface so
                  // the code block visually reads as a distinct region.
                  color: theme.bg,
                  borderRadius: BorderRadius.circular(6),
                  border: Border.all(color: theme.borderMid),
                ),
                child: SingleChildScrollView(
                  // SelectableText (not plain Text) so the user can highlight
                  // and manually copy portions of the DSL if they want to.
                  child: SelectableText(
                    // Show a friendly placeholder instead of a blank box when
                    // the graph has no content yet.
                    dsl.isEmpty ? '(empty graph)' : dsl,
                    style: GoogleFonts.courierPrime(
                        fontSize: 13, color: theme.textMid),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
      // Row of dialog actions, in the order they appear left-to-right.
      actions: [
        // "Export SVG" — converts the current graph geometry into an SVG
        // string and puts it on the clipboard, then confirms via a snackbar
        // and closes the dialog.
        TextButton(
          onPressed: () async {
            // Build the SVG representation from the raw node/line/arrow data
            // (not from the DSL — this is a direct geometric export).
            final svg = SvgExporter.export(
                nodes: nodes, lines: lines, startArrow: startArrow);
            // Write the SVG text to the system clipboard asynchronously.
            await Clipboard.setData(ClipboardData(text: svg));
            // Guard against using `context` after the widget tree above it
            // has been disposed while the await was in flight.
            if (!context.mounted) return;
            // Confirm the copy happened via a transient snackbar.
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('SVG copied to clipboard',
                    style: GoogleFonts.courierPrime()),
              ),
            );
            // Close the Export dialog itself (using the dialog's own ctx).
            Navigator.pop(ctx);
          },
          child: const Text('Export SVG'),
        ),
        // "Export LaTeX" — closes this dialog and immediately opens the
        // dedicated LaTeX export dialog (defined elsewhere) using the full
        // graph state (needed to derive TikZ/automaton LaTeX markup).
        TextButton(
          onPressed: () {
            Navigator.pop(ctx);
            showLatexExportDialog(context, graphState: graphState);
          },
          child: const Text('Export LaTeX'),
        ),
        // "Save" — persists the current DSL under the chosen name (falling
        // back to "Untitled" if the name field was left blank/whitespace),
        // then closes the dialog and confirms via snackbar.
        TextButton(
          onPressed: () {
            onSave(
              nameController.text.trim().isEmpty
                  ? 'Untitled'
                  : nameController.text.trim(),
              dsl,
            );
            Navigator.of(ctx).pop();
            ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Export saved')));
          },
          child: const Text('Save'),
        ),
        // "Copy" — re-copies the DSL text to the clipboard without closing
        // the dialog (useful if the user cleared their clipboard since the
        // dialog opened, since the initial copy happened before this dialog
        // was shown).
        TextButton(
          onPressed: () {
            Clipboard.setData(ClipboardData(text: dsl));
            ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Copied to clipboard')));
          },
          child: const Text('Copy'),
        ),
        // "Close" — dismiss the dialog with no further action.
        TextButton(
          onPressed: () => Navigator.of(ctx).pop(),
          child: const Text('Close'),
        ),
      ],
    ),
    // Once the dialog result completes (regardless of how it was dismissed),
    // dispose the TextEditingController to avoid leaking it — dialogs create
    // their own element tree that doesn't automatically dispose controllers
    // declared outside the builder.
  ).then((_) => nameController.dispose());
}

// ─────────────────────────────────────────────────────────────────────────────
//  showImportDialog
//
//  Displays the "Import" dialog: a free-text box where the user pastes DSL
//  text (or raw SVG markup — both are auto-detected and handled by the
//  caller-supplied `onImport`), plus Paste/Cancel/Import actions.
// ─────────────────────────────────────────────────────────────────────────────
void showImportDialog(
  BuildContext context, {
  // Attempts to import `text` into the graph. `isSvg` tells the caller which
  // parser to use. Returns null on success, or a human-readable error string
  // to display inline in the dialog on failure.
  required String? Function(String text, {required bool isSvg}) onImport,
}) {
  final theme = AppThemeNotifier.read(context);
  // Controller for the multi-line text box the user types/pastes into.
  final controller = TextEditingController();
  // Current validation error shown under the text field, if any. Lives
  // outside the StatefulBuilder's setState scope until reassigned there.
  String? errorText;

  // Placeholder text shown in the empty field to teach the DSL syntax by
  // example (node/edge declarations, labels, curve amount, start arrow, etc).
  const hint =
      'n0 = hello world\n'
      'n1 = yes and no\n'
      'hello world to yes and no = pears\n'
      'pears curve = 30\n'
      'apples\n'
      'apples to yes and no\n'
      'to apples\n'
      'apples to apples = 1\n'
      'apples = (0, 0)\n'
      'to apples length = 150\n'
      'apples is accepted';

  showDialog(
    context: context,
    // StatefulBuilder lets this dialog re-render itself (e.g. to show a
    // validation error) without needing a dedicated StatefulWidget class.
    builder: (ctx) => StatefulBuilder(
      // `setDialogState` triggers a rebuild scoped to just this builder.
      builder: (ctx, setDialogState) => AlertDialog(
        backgroundColor: theme.surface,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: BorderSide(color: theme.borderMid),
        ),
        title: Text(
          'Import',
          style: GoogleFonts.courierPrime(
              fontWeight: FontWeight.bold, color: theme.textLight),
        ),
        content: SizedBox(
          width: double.maxFinite,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Height-capped multi-line input box for pasted DSL/SVG text.
              ConstrainedBox(
                constraints: const BoxConstraints(maxHeight: 300),
                child: TextField(
                  controller: controller,
                  // `maxLines: null` + `expands: true` together make the
                  // field grow to fill its ConstrainedBox rather than
                  // auto-sizing to content, giving a proper multi-line editor.
                  maxLines: null,
                  expands: true,
                  style: GoogleFonts.courierPrime(
                      fontSize: 13, color: theme.textLight),
                  cursorColor: theme.accent,
                  decoration: InputDecoration(
                    border: const OutlineInputBorder(),
                    hintText: hint,
                    hintStyle: GoogleFonts.courierPrime(
                        fontSize: 11, color: theme.textDim),
                    // Shows the current validation error (if any) beneath
                    // the field, updated by setDialogState after a failed
                    // import attempt.
                    errorText: errorText,
                    errorMaxLines: 3,
                  ),
                ),
              ),
            ],
          ),
        ),
        actions: [
          // "Paste" — reads the system clipboard and overwrites the field
          // with its text content, if any.
          TextButton(
            onPressed: () async {
              final clip = await Clipboard.getData(Clipboard.kTextPlain);
              if (clip?.text != null) controller.text = clip!.text!;
            },
            child: const Text('Paste'),
          ),
          // "Cancel" — dismiss without importing anything.
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Cancel'),
          ),
          // "Import" — the primary action. Detects whether the pasted text
          // looks like SVG markup (case-insensitive check for an <svg>...
          // </svg> pair) versus plain DSL, then delegates to the caller's
          // `onImport`. On success the dialog closes and a confirmation
          // snackbar appears; on failure the returned error string is shown
          // inline instead of closing the dialog.
          FilledButton(
            onPressed: () {
              final text = controller.text.trim();
              final lower = text.toLowerCase();
              final isSvg =
                  lower.contains('<svg') && lower.contains('</svg>');
              final err = onImport(text, isSvg: isSvg);
              if (err == null) {
                Navigator.of(ctx).pop();
                ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('Import successful')));
              } else {
                // Re-render this dialog with the new error message, keeping
                // the user's typed text intact so they can fix it in place.
                setDialogState(() => errorText = err);
              }
            },
            child: const Text('Import'),
          ),
        ],
      ),
    ),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
//  showExportHistoryDialog
//
//  Displays the list of previously-saved exports (both plain graph exports
//  and "black box" machine exports). Each row supports: tap-to-load (or,
//  for black boxes, tap-to-open-the-runner), inserting as a black-box node
//  on the canvas, loading/importing into the current graph, exporting to
//  LaTeX, editing the saved DSL in place, and deleting the entry.
// ─────────────────────────────────────────────────────────────────────────────
void showExportHistoryDialog(
  BuildContext context, {
  // The live list of saved exports — mutated in place (e.g. removeAt) by
  // this dialog, so the caller's copy of the list stays in sync.
  required List<SavedExport> savedExports,
  // Imports a saved export's DSL into the current graph, replacing it.
  // Returns an error string on failure, or null on success.
  required String? Function(String dsl) onImportDsl,
  // Inserts a "black box" node onto the canvas backed by the given export's
  // DSL (i.e. a node whose internal behavior is defined by that sub-machine).
  required void Function(SavedExport export) onInsertBlackBox,
  // Called whenever the underlying list changes (edit or delete) so the
  // caller can persist the update (e.g. write back to local storage).
  required void Function() onListChanged,
}) {
  final theme = AppThemeNotifier.read(context);

  showDialog(
    context: context,
    builder: (ctx) {
      // StatefulBuilder so edits/deletes can refresh just this dialog's
      // list view without needing a full StatefulWidget class.
      return StatefulBuilder(
        builder: (context, setDialogState) {
          return AlertDialog(
            backgroundColor: theme.surface,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
              side: BorderSide(color: theme.borderMid),
            ),
            title: Text(
              'Saved Exports',
              style: GoogleFonts.courierPrime(
                  fontWeight: FontWeight.bold, color: theme.textLight),
            ),
            content: SizedBox(
              // Fixed size box (rather than shrink-wrap) so the dialog
              // doesn't jump around in size as the list is edited/deleted.
              width: double.maxFinite,
              height: 400,
              child: savedExports.isEmpty
                  // Empty state: centered placeholder message.
                  ? Center(
                      child: Text(
                        'No saved exports',
                        style: GoogleFonts.courierPrime(color: theme.textDim),
                      ),
                    )
                  // Otherwise render one ListTile per saved export.
                  : ListView.builder(
                      itemCount: savedExports.length,
                      itemBuilder: (context, index) {
                        // Defensive guard: the list can shrink out from under
                        // this builder (e.g. mid-delete) before Flutter has
                        // finished laying out already-scheduled items.
                        if (index >= savedExports.length) {
                          return const SizedBox.shrink();
                        }
                        final save = savedExports[index];
                        return ListTile(
                          title: Text(save.name,
                              style: TextStyle(color: theme.textLight)),
                          // Different leading icon depending on whether this
                          // entry is a black-box machine or a plain graph.
                          leading: save.isBlackBox
                              ? Icon(Icons.inbox_rounded,
                                  color: theme.textMid)
                              : Icon(Icons.account_tree_outlined,
                                  color: theme.textMid),
                          // Subtitle preview: for black boxes, a fixed label;
                          // for plain exports, either "(empty export)" or the
                          // DSL's first line as a quick preview.
                          subtitle: Text(
                            save.isBlackBox
                                ? 'Black box machine'
                                : (save.dsl.trim().isEmpty
                                    ? '(empty export)'
                                    : save.dsl.split('\n').first),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                            style: TextStyle(color: theme.textDim),
                          ),
                          // Tapping the row itself: black boxes open their
                          // runner dialog; plain exports close this dialog
                          // and import straight into the current graph
                          // (showing an error snackbar on failure).
                          onTap: () {
                            if (save.isBlackBox) {
                              showBlackBoxRunnerDialog(context, save: save);
                              return;
                            }
                            Navigator.of(ctx).pop();
                            final err = onImportDsl(save.dsl);
                            if (err != null) {
                              ScaffoldMessenger.of(context)
                                  .showSnackBar(SnackBar(
                                content: Text('Import error: $err'),
                              ));
                            }
                          },
                          // Row of trailing icon-button actions.
                          trailing: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              // Available for all exports: inserts a black box
                              // node onto the canvas backed by this saved DSL.
                              IconButton(
                                icon: Icon(Icons.add_box_outlined,
                                    color: theme.textMid),
                                tooltip: 'Insert as black box node',
                                onPressed: () {
                                  Navigator.of(ctx).pop();
                                  onInsertBlackBox(save);
                                },
                              ),
                              // The next two actions only make sense for
                              // plain (non-black-box) exports, since a black
                              // box's own DSL is its internal machine, not
                              // something you "Load"/"Export as LaTeX" from
                              // this menu directly.
                              if (!save.isBlackBox) ...[
                                // "Load" — opens a confirmation sub-dialog
                                // before replacing the current graph, since
                                // this is a destructive action.
                                IconButton(
                                  icon: Icon(
                                      Icons.input_rounded,
                                      color: theme.textMid),
                                  tooltip: 'Load',
                                  onPressed: () {
                                    showDialog(
                                      context: context,
                                      builder: (_) => AlertDialog(
                                        backgroundColor: theme.surface,
                                        shape: RoundedRectangleBorder(
                                          borderRadius:
                                              BorderRadius.circular(12),
                                          side:
                                              BorderSide(color: theme.borderMid),
                                        ),
                                        title: Text(
                                          'Load "${save.name}"?',
                                          style: TextStyle(
                                              color: theme.textLight),
                                        ),
                                        content: Text(
                                          'This will replace the current graph.',
                                          style: TextStyle(
                                              color: theme.textMid),
                                        ),
                                        actions: [
                                          // Cancel just closes the confirm
                                          // sub-dialog, leaving the history
                                          // dialog open underneath.
                                          TextButton(
                                            onPressed: () =>
                                                Navigator.pop(context),
                                            child: const Text('Cancel'),
                                          ),
                                          // Confirming: close both the
                                          // confirm sub-dialog and the
                                          // history dialog, then perform the
                                          // import, surfacing any error.
                                          FilledButton(
                                            onPressed: () {
                                              Navigator.pop(context);
                                              Navigator.of(ctx).pop();
                                              final err =
                                                  onImportDsl(save.dsl);
                                              if (err != null) {
                                                ScaffoldMessenger.of(
                                                        context)
                                                    .showSnackBar(SnackBar(
                                                  content: Text(
                                                      'Import error: $err'),
                                                ));
                                              }
                                            },
                                            child: const Text('Import'),
                                          ),
                                        ],
                                      ),
                                    );
                                  },
                                ),
                                // "Export as LaTeX" — parses the saved DSL
                                // back into a GraphState on the fly (it isn't
                                // kept as a GraphState in storage) and opens
                                // the LaTeX export dialog for it; a parse
                                // failure is surfaced as a snackbar instead
                                // of crashing.
                                IconButton(
                                  icon: Icon(Icons.code,
                                      color: theme.textMid),
                                  tooltip: 'Export as LaTeX',
                                  onPressed: () {
                                    try {
                                      final gs = DslCodec.importFromDsl(save.dsl);
                                      showLatexExportDialog(context, graphState: gs);
                                    } catch (e) {
                                      ScaffoldMessenger.of(context)
                                          .showSnackBar(SnackBar(
                                        content: Text('LaTeX export error: $e'),
                                      ));
                                    }
                                  },
                                ),
                              ],
                              // "Edit export" — available for every entry
                              // (including black boxes, since editing their
                              // internal DSL is meaningful). Opens the name +
                              // DSL editor sub-dialog; on a real save,
                              // notifies the caller and refreshes this list.
                              IconButton(
                                icon: Icon(Icons.edit, color: theme.textMid),
                                tooltip: 'Edit export',
                                onPressed: () {
                                  showEditSavedExportDialog(
                                    context,
                                    save: save,
                                    onSaved: () {
                                      onListChanged();
                                      setDialogState(() {});
                                    },
                                  );
                                },
                              ),
                              // "Delete" — removes the entry immediately
                              // (no confirmation), notifies the caller, and
                              // refreshes this dialog's list in place.
                              IconButton(
                                icon: const Icon(Icons.delete,
                                    color: Color(0xFFFF1744)),
                                onPressed: () {
                                  savedExports.removeAt(index);
                                  onListChanged();
                                  setDialogState(() {});
                                },
                              ),
                            ],
                          ),
                        );
                      },
                    ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.of(ctx).pop(),
                child: const Text('Close'),
              ),
            ],
          );
        },
      );
    },
  );
}

/// Opens an editor for a saved export's name and DSL code.
///
/// Works for both plain graph exports and black-box exports — a black box's
/// `dsl` is the DSL of its internal automaton, so editing it in place is the
/// same operation either way. [onSaved] is only invoked if the user actually
/// commits a change (i.e. taps Save on a valid DSL), not on Cancel.
void showEditSavedExportDialog(
  BuildContext context, {
  required SavedExport save,
  required void Function() onSaved,
}) {
  // Delegate to the stateful _EditSavedExportDialog widget (defined further
  // down) since this editor needs its own local state (two controllers plus
  // a validation-error string) that's easier to manage as a proper State
  // class than via StatefulBuilder.
  showDialog<bool>(
    context: context,
    builder: (_) => _EditSavedExportDialog(save: save),
    // The dialog resolves to `true` only when the user actually saved a
    // change (see _EditSavedExportDialogState._save, which pops `true`);
    // Cancel pops `false`/null, in which case onSaved is correctly skipped.
  ).then((changed) {
    if (changed == true) onSaved();
  });
}

// ─────────────────────────────────────────────────────────────────────────────
//  showBlackBoxRunnerDialog
//
//  Lets the user type one input string per line and run them all through a
//  saved "black box" machine, listing which ones are accepted (and, for TM
//  black boxes, what each accepted input transforms into on the tape).
// ─────────────────────────────────────────────────────────────────────────────
void showBlackBoxRunnerDialog(
  BuildContext context, {
  required SavedExport save,
}) {
  final theme = AppThemeNotifier.read(context);
  // Multi-line input controller: one candidate string per line.
  final inputController = TextEditingController();
  // Accumulated results text shown in the read-only output box below.
  String output = '';
  // Parse/validation error (e.g. malformed saved DSL), shown inline.
  String? errorText;

  showDialog(
    context: context,
    builder: (ctx) => StatefulBuilder(
      builder: (ctx, setDialogState) => AlertDialog(
        backgroundColor: theme.surface,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: BorderSide(color: theme.borderMid),
        ),
        // Dialog title is the export's own saved name.
        title: Text(
          save.name,
          style: GoogleFonts.courierPrime(
              fontWeight: FontWeight.bold, color: theme.textLight),
        ),
        content: SizedBox(
          width: 700,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Black box machine',
                style: TextStyle(color: theme.textMid),
              ),
              const SizedBox(height: 10),
              // Fixed 8-line input box for candidate strings.
              TextField(
                controller: inputController,
                maxLines: 8,
                style: GoogleFonts.courierPrime(
                    fontSize: 13, color: theme.textLight),
                cursorColor: theme.accent,
                decoration: InputDecoration(
                  border: const OutlineInputBorder(),
                  hintText: 'One input string per line',
                  hintStyle: TextStyle(color: theme.textDim),
                  errorText: errorText,
                ),
              ),
              const SizedBox(height: 10),
              // Read-only, scrollable output box showing accepted strings
              // (and, for TM machines, their transformed tape output).
              Container(
                width: double.infinity,
                constraints: const BoxConstraints(maxHeight: 220),
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  border: Border.all(color: theme.borderMid),
                  borderRadius: BorderRadius.circular(6),
                  color: theme.bg,
                ),
                child: SingleChildScrollView(
                  child: SelectableText(
                    // Placeholder text before the user has clicked "Run"
                    // (or after a run that yielded no output at all).
                    output.isEmpty
                        ? 'Output will list only accepted strings and changes.'
                        : output,
                    style: GoogleFonts.courierPrime(
                        fontSize: 13, color: theme.textMid),
                  ),
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Close'),
          ),
          // "Run" — executes every non-empty input line against the black
          // box's internal machine via the `_runBlackBox` helper below, then
          // either shows the parse error inline or repopulates the output
          // box with the accepted-string report.
          FilledButton(
            onPressed: () {
              final results = _runBlackBox(save, inputController.text);
              if (results.error != null) {
                setDialogState(() => errorText = results.error);
                return;
              }
              setDialogState(() {
                errorText = null;
                output = results.lines.isEmpty
                    ? '(no accepted strings)'
                    : results.lines.join('\n');
              });
            },
            child: const Text('Run'),
          ),
        ],
      ),
    ),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
//  _runBlackBox
//
//  Parses a saved export's DSL into a fresh GraphState, then simulates every
//  non-empty line of `rawInput` against it using whichever simulator matches
//  the graph's automata mode. Returns the accepted-input report lines, or an
//  error string if the DSL itself failed to parse.
// ─────────────────────────────────────────────────────────────────────────────
({List<String> lines, String? error}) _runBlackBox(
  SavedExport save,
  String rawInput,
) {
  GraphState state;
  try {
    // Re-parse the saved DSL fresh each run — the black box isn't kept as a
    // live GraphState between runs, only as text, keeping SavedExport simple
    // to serialize.
    state = DslCodec.importFromDsl(save.dsl);
  } catch (e) {
    // Surface a parse failure as a user-facing error rather than throwing,
    // since this saved DSL could in theory have been hand-edited into an
    // invalid state via the "Edit export" dialog before being run here.
    return (lines: const [], error: 'Black box parse error: $e');
  }

  // Split the textarea into individual candidate strings: strip stray
  // carriage returns (Windows-style line endings pasted in) and drop blank
  // lines so the user doesn't have to worry about trailing newlines.
  final rows = rawInput
      .split('\n')
      .map((line) => line.replaceAll('\r', ''))
      .where((line) => line.isNotEmpty)
      .toList();

  // Nothing to run — return an empty (non-error) result rather than
  // bothering to construct a simulator for zero inputs.
  if (rows.isEmpty) return (lines: const [], error: null);

  final output = <String>[];
  // Dispatch to the correct simulator based on which automata family this
  // saved machine represents. NDFA and Regex share the same simulator since
  // a converted regex is just a DFA by the time it's stored as DSL.
  switch (state.automataMode) {
    case AutomataMode.ndfa:
    case AutomataMode.regex:
      final sim = AutomataSimulator(nodes: state.nodes, lines: state.lines);
      for (final row in rows) {
        // Rebuild the simulator's internal step trace for this specific
        // input string, then just check whether it ends in acceptance —
        // the runner doesn't need the intermediate steps, only the verdict.
        sim.rebuild(row, startArrow: state.startArrow);
        if (sim.finalResult() == SimResult.accept) output.add(row);
      }
      break;
    case AutomataMode.pda:
      final sim = PdaSimulator(nodes: state.nodes, lines: state.lines);
      for (final row in rows) {
        sim.rebuild(row, startArrow: state.startArrow);
        if (sim.finalResult() == PdaSimResult.accept) output.add(row);
      }
      break;
    case AutomataMode.tm:
      final sim = TmSimulator(nodes: state.nodes, lines: state.lines);
      for (final row in rows) {
        sim.rebuild(row, startArrow: state.startArrow);
        // Turing machines don't have a single "final result" call like the
        // other simulators — drive the computation forward step by step
        // until computeNext() reports there's nothing left to do (halted,
        // or every branch died).
        while (sim.computeNext()) {}
        if (sim.result != TmResult.accept) continue;
        // For accepted TM inputs, also compute what the tape reads after
        // halting, since TMs can transform their input rather than just
        // accept/reject it verbatim.
        final transformed = _tmOutputString(sim);
        if (transformed == row) {
          // Input unchanged — report it plainly like the other modes do.
          output.add(row);
        } else {
          // Input transformed — show the "before -> after" mapping so the
          // user can see what the machine actually computed.
          output.add('$row -> $transformed');
        }
      }
      break;
  }

  return (lines: output, error: null);
}

// ─────────────────────────────────────────────────────────────────────────────
//  _tmOutputString
//
//  Reads the halted Turing machine's tape and returns its trimmed contents
//  as a plain string (blank cells stripped from both ends, blanks in the
//  interior preserved as empty strings so the join doesn't insert gaps).
// ─────────────────────────────────────────────────────────────────────────────
String _tmOutputString(TmSimulator sim) {
  final tape = sim.currentTape;
  // No tape snapshot available (e.g. machine never ran) — nothing to show.
  if (tape == null) return '';
  // Normalize blank cells (kBlank) to empty strings so they contribute
  // nothing when the final substring is joined together.
  final cells = tape.cells.map((c) => c == kBlank ? '' : c).toList();
  int start = 0;
  int end = cells.length;
  // Trim leading blank cells.
  while (start < end && cells[start].isEmpty) {
    start++;
  }
  // Trim trailing blank cells.
  while (end > start && cells[end - 1].isEmpty) {
    end--;
  }
  // Entire tape was blank.
  if (start >= end) return '';
  // Join only the meaningful (non-blank-bounded) middle section.
  return cells.sublist(start, end).join();
}

// ─────────────────────────────────────────────────────────────────────────────
//  Edit Saved Export — name + DSL code editor for showExportHistoryDialog
// ─────────────────────────────────────────────────────────────────────────────

class _EditSavedExportDialog extends StatefulWidget {
  const _EditSavedExportDialog({required this.save});

  // The SavedExport this dialog edits in place (mutated directly on Save,
  // rather than returning a copy — see _EditSavedExportDialogState._save).
  final SavedExport save;

  @override
  State<_EditSavedExportDialog> createState() =>
      _EditSavedExportDialogState();
}

class _EditSavedExportDialogState extends State<_EditSavedExportDialog> {
  // Pre-filled with the export's current name; `late final` since it depends
  // on `widget` which isn't available until the State object is constructed.
  late final TextEditingController _nameController =
      TextEditingController(text: widget.save.name);
  // Pre-filled with the export's current DSL text.
  late final TextEditingController _dslController =
      TextEditingController(text: widget.save.dsl);

  // Live validation error for the DSL field, updated on every keystroke via
  // _validate. Null means the current DSL text is acceptable to save.
  String? _dslError;

  @override
  void dispose() {
    // Both controllers were created by this State (not passed in), so this
    // State is responsible for disposing them to avoid leaking resources.
    _nameController.dispose();
    _dslController.dispose();
    super.dispose();
  }

  /// Empty DSL is allowed (an export can represent an empty graph); anything
  /// else must parse via the same codec the rest of the app uses, so a saved
  /// export can never be edited into a state the app itself can't load back.
  void _validate(String value) {
    if (value.trim().isEmpty) {
      // Blank DSL is explicitly valid — represents an empty graph export.
      setState(() => _dslError = null);
      return;
    }
    try {
      // Parse-only: the resulting GraphState is discarded here, this call
      // just exists to confirm the text is syntactically valid DSL.
      DslCodec.importFromDsl(value);
      setState(() => _dslError = null);
    } catch (e) {
      setState(() => _dslError = 'Invalid DSL: $e');
    }
  }

  void _save() {
    // Guard against saving while a validation error is still showing (the
    // Save button itself is also disabled in this state, but this is a
    // second line of defense in case _save is ever invoked another way).
    if (_dslError != null) return;
    final trimmedName = _nameController.text.trim();
    // Keep the previous name if the user cleared the name field entirely,
    // rather than allowing the export to end up with a blank name.
    widget.save.name = trimmedName.isEmpty ? widget.save.name : trimmedName;
    // DSL is saved as-is (not trimmed), preserving exactly what was typed.
    widget.save.dsl = _dslController.text;
    // Pop `true` so the caller (showEditSavedExportDialog) knows a real
    // change was committed and should invoke its onSaved callback.
    Navigator.of(context).pop(true);
  }

  @override
  Widget build(BuildContext context) {
    final theme = AppThemeNotifier.read(context);
    return AlertDialog(
      backgroundColor: theme.surface,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(color: theme.borderMid),
      ),
      title: Text(
        'Edit Export',
        style: GoogleFonts.courierPrime(
            fontWeight: FontWeight.bold, color: theme.textLight),
      ),
      content: SizedBox(
        // Fixed width (unlike the other dialogs' double.maxFinite) since
        // this dialog's content — two stacked text fields — doesn't need to
        // fill all available space.
        width: 480,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Editable name field.
            TextField(
              controller: _nameController,
              style: GoogleFonts.courierPrime(
                  color: theme.textLight, fontSize: 13),
              cursorColor: theme.accent,
              decoration: const InputDecoration(
                labelText: 'Name',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 14),
            // Label above the DSL editor, worded differently for black-box
            // exports (their DSL represents the *internal* machine, not a
            // graph the user directly interacts with on the canvas).
            Text(
              widget.save.isBlackBox
                  ? 'Internal DSL (black box machine)'
                  : 'DSL code',
              style: GoogleFonts.courierPrime(
                  fontSize: 12, color: theme.textMid),
            ),
            const SizedBox(height: 6),
            // Height-constrained (min 160 / max 260) multi-line DSL editor.
            // Re-validates on every change via onChanged: _validate.
            ConstrainedBox(
              constraints: const BoxConstraints(maxHeight: 260, minHeight: 160),
              child: TextField(
                controller: _dslController,
                onChanged: _validate,
                maxLines: null,
                expands: true,
                textAlignVertical: TextAlignVertical.top,
                style: GoogleFonts.courierPrime(
                    fontSize: 13, color: theme.textLight),
                cursorColor: theme.accent,
                decoration: InputDecoration(
                  border: const OutlineInputBorder(),
                  // Shows the live validation error from _validate, if any.
                  errorText: _dslError,
                  errorMaxLines: 3,
                ),
              ),
            ),
          ],
        ),
      ),
      actions: [
        // "Cancel" — pop `false` so the caller's `.then` skips onSaved.
        TextButton(
          onPressed: () => Navigator.of(context).pop(false),
          child: const Text('Cancel'),
        ),
        // "Save" — disabled (onPressed: null) whenever the DSL is currently
        // invalid, preventing the user from committing broken DSL.
        FilledButton(
          onPressed: _dslError == null ? _save : null,
          child: const Text('Save'),
        ),
      ],
    );
  }
}